### ISSUE TITLE
Create API option for twitter "plugin" that allows for auto-translation

### ISSUE THREAD

**Issue by Marak** [nodejitsu/kohai#5] opened 2011-05-17 02:11 UTC
We should expose an option for the twitter plugin that will enable the bot to attempt a auto-translation to english.

Based on the data we receive from twitter, we might be able to determine language, but most likely we will need to use translate.js auto-translate feature. I think translate.js supports this, but it might require a patch. Related issue: https://github.com/Marak/translate.js/issues/11

It would also be great to store the language detected per @username, so if we !tweet @username back at some point, it will auto-translate to @usernames original language. <=== Twitter BabelFish

**Comment by AvianFlu** [comment] 2011-05-22 19:17
At least partially addressed by #35

**Comment by AvianFlu** [comment] 2011-05-27 16:44
"Important: The Google Translate API has been officially deprecated as of May 26, 2011. Due to the substantial economic burden caused by extensive abuse, the number of requests you may make per day will be limited and the API will be shut off completely on December 1, 2011. For website translations, we encourage you to use the Google Translate Element."

Seemed relevant.

**Comment by AvianFlu** [comment] 2011-05-29 16:46
Until translation is implemented, kohai is going to drop all non-english tweets.  

https://github.com/nodejitsu/kohai/commit/a1c06aa25f8d33b541de95f06a29e5b7e0afc84a

**Comment by AvianFlu** [comment] 2011-10-20 21:31
This is more of a hook.io-twitter issue, and no immediate solution has presented itself.  Closing issue.

**Closed as completed by AvianFlu** 2011-10-20 21:31 UTC
